version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - npm run build:zip

  post_build:
    commands:
      - echo Build completed on `date`
      - pwd

artifacts:
  files:
    - MyXD.zip
    - appspec.yml
    - deploy.sh

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
