version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - pwd
    run-as: root

  build:
    commands:
      - echo Build Starting on `date`
      - npm run build:zip

  post_build:
    commands:
      - echo Build completed on `date`
      - pwd

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
