version: 0.2

phases:
  install:
    commands:
      - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
      - npm config set "//npm.fontawesome.com/:_authToken" 805BDB06-0B0E-48D6-A761-61C314D95F29
      - npm install
    run-as: root

  build:
    commands:
      - echo Build Starting !
      - npm run build:zip

  post_build:
    commands:
      - echo Build completed !

artifacts:
  files:
    - MyXD.zip
    - appspec.yml
    - deploy.sh

cache:
  paths:
    - 'node_modules/**/*'
