name: MYXD

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*
      - MYXD-141

jobs:
  build:
    name : MYXD action
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: echo Hello
        run: echo "Hello"


